"""catalog and inventory

Revision ID: phase2_0001
Revises: phase1_0001
Create Date: 2026-07-31 23:58:14.677665
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "phase2_0001"
down_revision: str | Sequence[str] | None = "phase1_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("logo_path", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brands_created_by"), "brands", ["created_by"], unique=False)
    op.create_index(op.f("ix_brands_is_active"), "brands", ["is_active"], unique=False)
    op.create_index("ix_brands_slug", "brands", ["slug"], unique=True)
    op.create_index(op.f("ix_brands_updated_by"), "brands", ["updated_by"], unique=False)
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("image_path", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_created_by"), "categories", ["created_by"], unique=False)
    op.create_index(op.f("ix_categories_is_active"), "categories", ["is_active"], unique=False)
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_index("ix_categories_slug", "categories", ["slug"], unique=True)
    op.create_index(op.f("ix_categories_updated_by"), "categories", ["updated_by"], unique=False)
    op.create_table(
        "price_tiers",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_price_tiers_code", "price_tiers", ["code"], unique=True)
    op.create_index(op.f("ix_price_tiers_created_by"), "price_tiers", ["created_by"], unique=False)
    op.create_index(op.f("ix_price_tiers_is_active"), "price_tiers", ["is_active"], unique=False)
    op.create_index(op.f("ix_price_tiers_updated_by"), "price_tiers", ["updated_by"], unique=False)
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_settings_created_by"), "settings", ["created_by"], unique=False)
    op.create_index("ix_settings_key", "settings", ["key"], unique=True)
    op.create_index(op.f("ix_settings_updated_by"), "settings", ["updated_by"], unique=False)
    op.create_table(
        "warehouses",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_warehouses_code", "warehouses", ["code"], unique=True)
    op.create_index(op.f("ix_warehouses_created_by"), "warehouses", ["created_by"], unique=False)
    op.create_index(op.f("ix_warehouses_is_active"), "warehouses", ["is_active"], unique=False)
    op.create_index(op.f("ix_warehouses_updated_by"), "warehouses", ["updated_by"], unique=False)
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=240), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column(
            "product_type",
            sa.Enum(
                "PRESCRIPTION",
                "OTC",
                "SPECIALTY",
                "NUTRACEUTICAL",
                "MEDICAL_DEVICE",
                "CONSUMABLE",
                name="product_type",
            ),
            server_default="OTC",
            nullable=False,
        ),
        sa.Column(
            "requires_prescription", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("registration_no", sa.String(length=120), nullable=True),
        sa.Column("generic_name", sa.String(length=200), nullable=True),
        sa.Column("strength", sa.String(length=100), nullable=True),
        sa.Column("pack_size", sa.String(length=100), nullable=True),
        sa.Column(
            "unit",
            sa.Enum("PCS", "BOX", "STRIP", "BOTTLE", "PACK", "VIAL", "TUBE", name="product_unit"),
            server_default="PCS",
            nullable=False,
        ),
        sa.Column("hsn_code", sa.String(length=50), nullable=True),
        sa.Column("base_mrp", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("low_stock_threshold", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum("UNVERIFIED", "VERIFIED", name="verification_status"),
            server_default="UNVERIFIED",
            nullable=False,
        ),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["verified_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_brand_id"), "products", ["brand_id"], unique=False)
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(op.f("ix_products_created_by"), "products", ["created_by"], unique=False)
    op.create_index(op.f("ix_products_is_active"), "products", ["is_active"], unique=False)
    op.create_index(op.f("ix_products_product_type"), "products", ["product_type"], unique=False)
    op.create_index("ix_products_sku", "products", ["sku"], unique=True)
    op.create_index("ix_products_slug", "products", ["slug"], unique=True)
    op.create_index(op.f("ix_products_updated_by"), "products", ["updated_by"], unique=False)
    op.create_index(
        op.f("ix_products_verification_status"), "products", ["verification_status"], unique=False
    )
    op.create_index(op.f("ix_products_verified_by"), "products", ["verified_by"], unique=False)
    op.create_table(
        "product_batches",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("batch_number", sa.String(length=100), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("quantity_available", sa.Integer(), server_default="0", nullable=False),
        sa.Column("quantity_reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DEPLETED", "EXPIRED", "QUARANTINED", name="batch_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "cost_price IS NULL OR cost_price >= 0", name="ck_product_batches_cost_nonnegative"
        ),
        sa.CheckConstraint(
            "quantity_available >= 0", name="ck_product_batches_available_nonnegative"
        ),
        sa.CheckConstraint(
            "quantity_reserved >= 0 AND quantity_reserved <= quantity_available",
            name="ck_product_batches_reserved_valid",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_batches_created_by"), "product_batches", ["created_by"], unique=False
    )
    op.create_index(
        "ix_product_batches_expiry_date", "product_batches", ["expiry_date"], unique=False
    )
    op.create_index(
        "ix_product_batches_product_id", "product_batches", ["product_id"], unique=False
    )
    op.create_index("ix_product_batches_status", "product_batches", ["status"], unique=False)
    op.create_index(
        op.f("ix_product_batches_updated_by"), "product_batches", ["updated_by"], unique=False
    )
    op.create_index(
        "ix_product_batches_warehouse_id", "product_batches", ["warehouse_id"], unique=False
    )
    op.create_index(
        "uq_product_batches_product_warehouse_number",
        "product_batches",
        ["product_id", "warehouse_id", "batch_number"],
        unique=True,
    )
    op.create_table(
        "product_images",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_images_created_by"), "product_images", ["created_by"], unique=False
    )
    op.create_index("ix_product_images_product_id", "product_images", ["product_id"], unique=False)
    op.create_index(
        op.f("ix_product_images_updated_by"), "product_images", ["updated_by"], unique=False
    )
    op.create_index(
        "uq_product_images_primary",
        "product_images",
        ["product_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "product_prices",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("price_tier_id", sa.UUID(), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("mrp", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("discount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "discount IS NULL OR discount >= 0", name="ck_product_prices_discount_nonnegative"
        ),
        sa.CheckConstraint("mrp IS NULL OR mrp >= 0", name="ck_product_prices_mrp_nonnegative"),
        sa.CheckConstraint("price >= 0", name="ck_product_prices_price_nonnegative"),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["price_tier_id"], ["price_tiers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_prices_created_by"), "product_prices", ["created_by"], unique=False
    )
    op.create_index(
        "ix_product_prices_price_tier_id", "product_prices", ["price_tier_id"], unique=False
    )
    op.create_index("ix_product_prices_product_id", "product_prices", ["product_id"], unique=False)
    op.create_index(
        op.f("ix_product_prices_updated_by"), "product_prices", ["updated_by"], unique=False
    )
    op.create_index(
        "uq_product_prices_product_tier",
        "product_prices",
        ["product_id", "price_tier_id"],
        unique=True,
    )
    op.create_table(
        "stock_movements",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "INBOUND",
                "OUTBOUND",
                "ADJUSTMENT",
                "RETURN",
                "TRANSFER",
                "INITIAL",
                name="stock_movement_type",
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "reference_type",
            sa.Enum(
                "ORDER", "MANUAL", "RETURN", "TRANSFER", "INITIAL", name="stock_reference_type"
            ),
            nullable=False,
        ),
        sa.Column("reference_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity <> 0", name="ck_stock_movements_quantity_nonzero"),
        sa.ForeignKeyConstraint(["batch_id"], ["product_batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["admin_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_stock_movements_batch_id", "stock_movements", ["batch_id"], unique=False)
    op.create_index(
        "ix_stock_movements_created_at", "stock_movements", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_created_by"), "stock_movements", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_movement_type"), "stock_movements", ["movement_type"], unique=False
    )
    op.create_index(
        "ix_stock_movements_product_id", "stock_movements", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_reference_type"),
        "stock_movements",
        ["reference_type"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_warehouse_id", "stock_movements", ["warehouse_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_movements_warehouse_id", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_reference_type"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_product_id", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_movement_type"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_created_by"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_created_at", table_name="stock_movements")
    op.drop_index("ix_stock_movements_batch_id", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index("uq_product_prices_product_tier", table_name="product_prices")
    op.drop_index(op.f("ix_product_prices_updated_by"), table_name="product_prices")
    op.drop_index("ix_product_prices_product_id", table_name="product_prices")
    op.drop_index("ix_product_prices_price_tier_id", table_name="product_prices")
    op.drop_index(op.f("ix_product_prices_created_by"), table_name="product_prices")
    op.drop_table("product_prices")
    op.drop_index(
        "uq_product_images_primary",
        table_name="product_images",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_index(op.f("ix_product_images_updated_by"), table_name="product_images")
    op.drop_index("ix_product_images_product_id", table_name="product_images")
    op.drop_index(op.f("ix_product_images_created_by"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index("uq_product_batches_product_warehouse_number", table_name="product_batches")
    op.drop_index("ix_product_batches_warehouse_id", table_name="product_batches")
    op.drop_index(op.f("ix_product_batches_updated_by"), table_name="product_batches")
    op.drop_index("ix_product_batches_status", table_name="product_batches")
    op.drop_index("ix_product_batches_product_id", table_name="product_batches")
    op.drop_index("ix_product_batches_expiry_date", table_name="product_batches")
    op.drop_index(op.f("ix_product_batches_created_by"), table_name="product_batches")
    op.drop_table("product_batches")
    op.drop_index(op.f("ix_products_verified_by"), table_name="products")
    op.drop_index(op.f("ix_products_verification_status"), table_name="products")
    op.drop_index(op.f("ix_products_updated_by"), table_name="products")
    op.drop_index("ix_products_slug", table_name="products")
    op.drop_index("ix_products_sku", table_name="products")
    op.drop_index(op.f("ix_products_product_type"), table_name="products")
    op.drop_index(op.f("ix_products_is_active"), table_name="products")
    op.drop_index(op.f("ix_products_created_by"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index(op.f("ix_products_brand_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_warehouses_updated_by"), table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_is_active"), table_name="warehouses")
    op.drop_index(op.f("ix_warehouses_created_by"), table_name="warehouses")
    op.drop_index("ix_warehouses_code", table_name="warehouses")
    op.drop_table("warehouses")
    op.drop_index(op.f("ix_settings_updated_by"), table_name="settings")
    op.drop_index("ix_settings_key", table_name="settings")
    op.drop_index(op.f("ix_settings_created_by"), table_name="settings")
    op.drop_table("settings")
    op.drop_index(op.f("ix_price_tiers_updated_by"), table_name="price_tiers")
    op.drop_index(op.f("ix_price_tiers_is_active"), table_name="price_tiers")
    op.drop_index(op.f("ix_price_tiers_created_by"), table_name="price_tiers")
    op.drop_index("ix_price_tiers_code", table_name="price_tiers")
    op.drop_table("price_tiers")
    op.drop_index(op.f("ix_categories_updated_by"), table_name="categories")
    op.drop_index("ix_categories_slug", table_name="categories")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_is_active"), table_name="categories")
    op.drop_index(op.f("ix_categories_created_by"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_brands_updated_by"), table_name="brands")
    op.drop_index("ix_brands_slug", table_name="brands")
    op.drop_index(op.f("ix_brands_is_active"), table_name="brands")
    op.drop_index(op.f("ix_brands_created_by"), table_name="brands")
    op.drop_table("brands")
    bind = op.get_bind()
    sa.Enum(name="stock_reference_type").drop(bind, checkfirst=True)
    sa.Enum(name="stock_movement_type").drop(bind, checkfirst=True)
    sa.Enum(name="batch_status").drop(bind, checkfirst=True)
    sa.Enum(name="verification_status").drop(bind, checkfirst=True)
    sa.Enum(name="product_unit").drop(bind, checkfirst=True)
    sa.Enum(name="product_type").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
